
const characters = {

	// tdr_liubei: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["rerende", "rejijiang"],
	// 	isZhugong: true,
	// },

	tdr_guanyu: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["tdr_wusheng", "tdr_yijue"],
		dieAudios: ["sb_guanyu"]
	},

	tdr_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tdr_zhiheng", "tdr_tongye"],
		dieAudios: ["sb_sunquan"]
	},


	// tdr_zhangfei: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["olpaoxiao", "oltishen"],
	// },
	// tdr_zhaoyun: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["ollongdan", "olyajiao"],
	// },

	// tdr_machao: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["mashu", "retieji"],
	// },



	// tdr_zhuzhi: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["reanguo"],
	// },
	// dc_caozhi: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["reluoying", "dcjiushi"],
	// },
	// ol_huangzhong: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["xinliegong", "remoshi"],
	// },
	// tdr_wenpin: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 5,
	// 	skills: ["rezhenwei"],
	// },
	// tdr_guanzhang: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["fuhun", "retongxin"],
	// 	names: "关|兴-张|苞",
	// },
	// tdr_mazhong: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["refuman"],
	// },
	// dc_chenqun: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["repindi", "dcfaen"],
	// },
	// tdr_sundeng: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["rekuangbi"],
	// },
	// tdr_caiyong: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["rebizhuan", "retongbo"],
	// },
	// tdr_chengong: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["remingce", "zhichi"],
	// },
	// tdr_xunyou: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["reqice", "rezhiyu"],
	// 	clans: ["颍川荀氏"],
	// },
	// dc_liru: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["xinjuece", "dcmieji", "dcfencheng"],
	// },
	// tdr_zhuhuan: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["refenli", "repingkou"],
	// },
	// ol_dianwei: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["olqiangxi", "olninge"],
	// },
	// tdr_sp_taishici: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["rejixu"],
	// 	names: "太史|慈",
	// },
	// tdr_liufeng: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["rexiansi"],
	// },
	// ol_xunyu: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["quhu", "oljieming"],
	// 	clans: ["颍川荀氏"],
	// },
	// tdr_liuchen: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["rezhanjue", "reqinwang"],
	// 	isZhugong: true,
	// },
	// dc_gongsunzan: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["dcyicong", "dcqiaomeng"],
	// 	names: "公孙|瓒",
	// },
	// tdr_duji: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["reandong", "reyingshi"],
	// },
	// tdr_jushou: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["dcjianying", "dcshibei"],
	// },
	// tdr_zhanghe: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["reqiaobian"],
	// },
	// dc_xushu: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["rezhuhai", "xsqianxin"],
	// },
	// xin_gaoshun: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["decadexianzhen", "decadejinjiu"],
	// },
	// tdr_guohuanghou: {
	// 	sex: "female",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["rejiaozhao", "redanxin"],
	// 	names: "郭|null",
	// },
	// tdr_xiahoushi: {
	// 	sex: "female",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["reqiaoshi", "reyanyu"],
	// 	names: "夏侯|null",
	// },
	// ol_lusu: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["olhaoshi", "oldimeng"],
	// },
	// tdr_jiaxu: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["rewansha", "reluanwu", "reweimu"],
	// },
	// tdr_guyong: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["reshenxing", "rebingyi"],
	// },
	// xin_zhonghui: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["xinquanji", "xinzili"],
	// 	clans: ["颍川钟氏"],
	// },
	// tdr_caifuren: {
	// 	sex: "female",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["reqieting", "rexianzhou"],
	// 	names: "蔡|null",
	// },
	// tdr_guanping: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["relongyin", "jiezhong"],
	// },
	// tdr_guotufengji: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["rejigong", "shifei"],
	// 	names: "郭|图-逢|记",
	// },
	// tdr_zhoucang: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["rezhongyong"],
	// },
	// ol_zhurong: {
	// 	sex: "female",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["juxiang", "lieren", "changbiao"],
	// 	doubleGroup: ["shu", "qun"],
	// 	names: "null|null",
	// },
	// tdr_zhangchunhua: {
	// 	sex: "female",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["rejueqing", "shangshi"],
	// },
	// tdr_gongsunyuan: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["rehuaiyi"],
	// 	names: "公孙|渊",
	// },
	// tdr_caozhen: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["residi"],
	// },
	// tdr_fuhuanghou: {
	// 	sex: "female",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["rezhuikong", "reqiuyuan"],
	// },
	// tdr_fazheng: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["reenyuan", "rexuanhuo"],
	// },
	// xin_lingtong: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["decadexuanfeng", "yongjin"],
	// },
	// xin_liubiao: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["decadezishou", "decadezongshi"],
	// },
	// tdr_caoxiu: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["qianju", "reqingxi"],
	// },
	// tdr_sunxiu: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["reyanzhu", "rexingxue", "zhaofu"],
	// 	isZhugong: true,
	// },
	// ol_dengai: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["oltuntian", "olzaoxian"],
	// },
	// tdr_gongsunzan: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["reqiaomeng", "reyicong"],
	// 	names: "公孙|瓒",
	// },
	// tdr_manchong: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["rejunxing", "yuce"],
	// },
	// xin_yufan: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["xinzhiyan", "xinzongxuan"],
	// },
	// dc_bulianshi: {
	// 	sex: "female",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["dcanxu", "dczhuiyi"],
	// },
	// tdr_hanhaoshihuan: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["reshenduan", "reyonglve"],
	// 	names: "韩|浩-史|涣",
	// },
	// tdr_panzhangmazhong: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["reduodao", "reanjian"],
	// 	names: "潘|璋-马|忠",
	// },
	// tdr_wangyi: {
	// 	sex: "female",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["zhenlie", "miji"],
	// },
	// tdr_madai: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["mashu", "reqianxi"],
	// },
	// xin_xusheng: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["decadepojun"],
	// },
	// tdr_taishici: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["tianyi", "hanzhan"],
	// 	names: "太史|慈",
	// },
	// tdr_masu: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["resanyao", "rezhiman"],
	// },
	// tdr_sunluban: {
	// 	sex: "female",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["rechanhui", "rejiaojin"],
	// },
	// xin_handang: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["xingongji", "xinjiefan"],
	// },
	// yujin_yujin: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["decadezhenjun"],
	// 	dieAudios: ["xin_yujin.mp3"],
	// },
	// tdr_caozhang: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["xinjiangchi"],
	// },
	// tdr_chengpu: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["ollihuo", "rechunlao"],
	// },
	// tdr_quancong: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["xinyaoming"],
	// },
	// tdr_liaohua: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["xindangxian", "xinfuli"],
	// },
	// tdr_guohuai: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["decadejingce"],
	// },
	// tdr_wuyi: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["xinbenxi"],
	// 	clans: ["陈留吴氏"],
	// },
	// tdr_zhuran: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["xindanshou"],
	// },
	// ol_pangtong: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["ollianhuan", "olniepan"],
	// },
	// tdr_zhangyi: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 5,
	// 	skills: ["rewurong", "reshizhi"],
	// },
	// xin_wuguotai: {
	// 	sex: "female",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["xinganlu", "xinbuyi"],
	// 	names: "丁|null",
	// },
	// tdr_caocao: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["new_rejianxiong", "rehujia"],
	// 	isZhugong: true,
	// },
	// tdr_simayi: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["refankui", "reguicai"],
	// 	names: "司马|懿",
	// },
	// tdr_guojia: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["tiandu", "new_reyiji"],
	// },
	// tdr_zhangliao: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["new_retuxi"],
	// },
	// tdr_xuzhu: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["new_reluoyi"],
	// },
	// tdr_xiahoudun: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["reganglie", "new_qingjian"],
	// 	names: "夏侯|惇",
	// },

	// tdr_zhouyu: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["reyingzi", "refanjian"],
	// },
	// tdr_lvmeng: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["keji", "qinxue", "rebotu"],
	// },
	// tdr_ganning: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["qixi", "fenwei"],
	// },
	// tdr_luxun: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["reqianxun", "relianying"],
	// 	clans: ["吴郡陆氏"],
	// },
	// tdr_daqiao: {
	// 	sex: "female",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["reguose", "liuli"],
	// 	names: "桥|null",
	// },
	// tdr_huanggai: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["rekurou", "zhaxiang"],
	// },
	// tdr_lvbu: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 5,
	// 	skills: ["wushuang", "new_liyu"],
	// },
	// tdr_huatuo: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["jijiu", "new_reqingnang"],
	// },

	// tdr_diaochan: {
	// 	sex: "female",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["lijian", "rebiyue"],
	// 	names: "null|null",
	// },
	// tdr_huangyueying: {
	// 	sex: "female",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["rejizhi", "reqicai"],
	// },

	// tdr_sunshangxiang: {
	// 	sex: "female",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["xiaoji", "rejieyin"],
	// },
	// tdr_zhenji: {
	// 	sex: "female",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["reluoshen", "qingguo"],
	// },
	// tdr_zhugeliang: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["reguanxing", "kongcheng"],
	// 	names: "诸葛|亮",
	// },
	// tdr_huaxiong: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 6,
	// 	skills: ["reyaowu", "shizhan"],
	// },

	// tdr_zhangjiao: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["xinleiji", "xinguidao", "xinhuangtian"],
	// 	isZhugong: true,
	// },
	// xin_yuji: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["reguhuo"],
	// },
	// tdr_zuoci: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["rehuashen", "rexinsheng"],
	// },

	// ol_xiahouyuan: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["xinshensu", "shebian"],
	// 	names: "夏侯|渊",
	// },
	// caoren: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["xinjushou", "xinjiewei"],
	// },
	// ol_weiyan: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["xinkuanggu", "reqimou"],
	// },
	// ol_xiaoqiao: {
	// 	sex: "female",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["oltianxiang", "olhongyan", "piaoling"],
	// 	names: "桥|null",
	// },
	// zhoutai: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["buqu", "fenji"],
	// },
	// ol_pangde: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["mashu", "rejianchu"],
	// },
	// ol_xuhuang: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["olduanliang", "oljiezi"],
	// },
	// ol_sp_zhugeliang: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["bazhen", "olhuoji", "olkanpo", "cangzhuo"],
	// 	names: "诸葛|亮",
	// },
	// ol_yanwen: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["olshuangxiong"],
	// 	names: "颜|良-文|丑",
	// },
	// ol_yuanshao: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["olluanji", "olxueyi"],
	// 	isZhugong: true,
	// },
	// tdr_menghuo: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["huoshou", "rezaiqi", "twqiushou"],
	// 	isZhugong: true,
	// 	doubleGroup: ["shu", "qun"],
	// },
	// ol_dongzhuo: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 8,
	// 	skills: ["oljiuchi", "roulin", "benghuai", "olbaonue"],
	// 	isZhugong: true,
	// },
	// ol_sunjian: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	maxHp: 5,
	// 	skills: ["gzyinghun", "wulie", "twpolu"],
	// 	isZhugong: true,
	// },
	// tdr_caopi: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["rexingshang", "refangzhu", "songwei"],
	// 	isZhugong: true,
	// },
	// ol_jiangwei: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["oltiaoxin", "olzhiji"],
	// },
	// ol_caiwenji: {
	// 	sex: "female",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["olbeige", "duanchang"],
	// },
	// ol_liushan: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["xiangle", "olfangquan", "olruoyu"],
	// 	isZhugong: true,
	// },

	// tdr_sunce: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["oljiang", "olhunzi", "olzhiba"],
	// 	isZhugong: true,
	// },
	// tdr_jianyong: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["reqiaoshui", "jyzongshi"],
	// },
};

export default characters;
